import Head from 'next/head'
import Banner from '../components/Banner'
import CoreFeature from '../components/CoreFeature'
import Feature from '../components/Feature'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Package from '../components/Package'
import QualityFeature from '../components/QualityFeature'
import Services from '../components/Services'
import Subscribe from '../components/Subscribe'
import Team from '../components/Team'
import Testimonial from '../components/Testimonials'
import WorkFlow from '../components/WorkFlow'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <Feature />
      <Services />
      <QualityFeature/>
      <CoreFeature />
      <WorkFlow />
      <Package />
      <Team />
      <Testimonial />
      <Subscribe />
      <Footer/>
    </div>
  )
}
